### ISSUE TITLE
Electricity consumption wrongly reported.

### ISSUE THREAD

**Issue by ggael** [thangdnsf/consumption-analysis#1]
There is an issue in the reporting of the electricity consumption. For instance, I get:

• Spent 32MB
• GHG : 0.25 gCO2e 
• electricity : 25852 Wh

whereas the 0.25 gCO2e seems to match "(7.20e-11+1.52e-10)*32*1e6*0.035*1000", with the "0.035" coming from device.GHG for France, I expect the electricity to be:

"(7.20e-11+1.52e-10)*32*1e6*1000" = 7.16 Wh

and not the extravagant 25852 Wh !

**Comment by thangdnsf** [comment]
exactly, I really got a mistake there. 
Thank for your contribution!
